//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LIVEDBEntities6 : DbContext
    {
        public LIVEDBEntities6()
            : base("name=LIVEDBEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HC_CLIENT_BRANCH> HC_CLIENT_BRANCH { get; set; }
        public virtual DbSet<HC_CLIENTS> HC_CLIENTS { get; set; }
        public virtual DbSet<HC_CONS_BILLING> HC_CONS_BILLING { get; set; }
        public virtual DbSet<HC_USERS> HC_USERS { get; set; }
        public virtual DbSet<HCM_COUNTRIES> HCM_COUNTRIES { get; set; }
        public virtual DbSet<HC_RESUME_BANK> HC_RESUME_BANK { get; set; }
        public virtual DbSet<IHD_Timesheet_Template> IHD_Timesheet_Template { get; set; }
        public virtual DbSet<hc_client_user> hc_client_user { get; set; }
        public virtual DbSet<IHD_Country_EmailID> IHD_Country_EmailID { get; set; }
        public virtual DbSet<HC_EMAIL_SENT_LOG> HC_EMAIL_SENT_LOG { get; set; }
        public virtual DbSet<HC_Comment_Log> HC_Comment_Log { get; set; }
    
        public virtual ObjectResult<TiemSheetBarChartDashBoard_viewall_Result> TiemSheetBarChartDashBoard_viewall(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TiemSheetBarChartDashBoard_viewall_Result>("TiemSheetBarChartDashBoard_viewall", useridParameter);
        }
    
        public virtual ObjectResult<TimeSheetBarChart_Result> TimeSheetBarChart(Nullable<long> userid, string countryid, Nullable<long> unbilledYear, string unbilledMonth)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var countryidParameter = countryid != null ?
                new ObjectParameter("Countryid", countryid) :
                new ObjectParameter("Countryid", typeof(string));
    
            var unbilledYearParameter = unbilledYear.HasValue ?
                new ObjectParameter("UnbilledYear", unbilledYear) :
                new ObjectParameter("UnbilledYear", typeof(long));
    
            var unbilledMonthParameter = unbilledMonth != null ?
                new ObjectParameter("UnbilledMonth", unbilledMonth) :
                new ObjectParameter("UnbilledMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimeSheetBarChart_Result>("TimeSheetBarChart", useridParameter, countryidParameter, unbilledYearParameter, unbilledMonthParameter);
        }
    
        public virtual ObjectResult<TimeSheetBarChartDashBoardViewAll_Result> TimeSheetBarChartDashBoardViewAll(Nullable<long> userid, string countryid, Nullable<long> unbilledYear, string unbilledMonth)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var countryidParameter = countryid != null ?
                new ObjectParameter("Countryid", countryid) :
                new ObjectParameter("Countryid", typeof(string));
    
            var unbilledYearParameter = unbilledYear.HasValue ?
                new ObjectParameter("UnbilledYear", unbilledYear) :
                new ObjectParameter("UnbilledYear", typeof(long));
    
            var unbilledMonthParameter = unbilledMonth != null ?
                new ObjectParameter("UnbilledMonth", unbilledMonth) :
                new ObjectParameter("UnbilledMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimeSheetBarChartDashBoardViewAll_Result>("TimeSheetBarChartDashBoardViewAll", useridParameter, countryidParameter, unbilledYearParameter, unbilledMonthParameter);
        }
    
        public virtual ObjectResult<TimeSheetDetailsAgainstCandidate_Result> TimeSheetDetailsAgainstCandidate(string employeeid)
        {
            var employeeidParameter = employeeid != null ?
                new ObjectParameter("Employeeid", employeeid) :
                new ObjectParameter("Employeeid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimeSheetDetailsAgainstCandidate_Result>("TimeSheetDetailsAgainstCandidate", employeeidParameter);
        }
    
        public virtual ObjectResult<TimeSheetGrid_Result> TimeSheetGrid(string clientid, string lOB, Nullable<long> unbilledYear, string unbilledMonth)
        {
            var clientidParameter = clientid != null ?
                new ObjectParameter("clientid", clientid) :
                new ObjectParameter("clientid", typeof(string));
    
            var lOBParameter = lOB != null ?
                new ObjectParameter("LOB", lOB) :
                new ObjectParameter("LOB", typeof(string));
    
            var unbilledYearParameter = unbilledYear.HasValue ?
                new ObjectParameter("UnbilledYear", unbilledYear) :
                new ObjectParameter("UnbilledYear", typeof(long));
    
            var unbilledMonthParameter = unbilledMonth != null ?
                new ObjectParameter("UnbilledMonth", unbilledMonth) :
                new ObjectParameter("UnbilledMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimeSheetGrid_Result>("TimeSheetGrid", clientidParameter, lOBParameter, unbilledYearParameter, unbilledMonthParameter);
        }
    
        public virtual ObjectResult<timesheetmailhistory_Result> timesheetmailhistory(string employeeno)
        {
            var employeenoParameter = employeeno != null ?
                new ObjectParameter("employeeno", employeeno) :
                new ObjectParameter("employeeno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timesheetmailhistory_Result>("timesheetmailhistory", employeenoParameter);
        }
    
        public virtual ObjectResult<TimeSheetPieChartForAppClientPage_Result> TimeSheetPieChartForAppClientPage(Nullable<int> unbilledYear, string unbilledMonth, string clientid, string lOB)
        {
            var unbilledYearParameter = unbilledYear.HasValue ?
                new ObjectParameter("UnbilledYear", unbilledYear) :
                new ObjectParameter("UnbilledYear", typeof(int));
    
            var unbilledMonthParameter = unbilledMonth != null ?
                new ObjectParameter("UnbilledMonth", unbilledMonth) :
                new ObjectParameter("UnbilledMonth", typeof(string));
    
            var clientidParameter = clientid != null ?
                new ObjectParameter("Clientid", clientid) :
                new ObjectParameter("Clientid", typeof(string));
    
            var lOBParameter = lOB != null ?
                new ObjectParameter("LOB", lOB) :
                new ObjectParameter("LOB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimeSheetPieChartForAppClientPage_Result>("TimeSheetPieChartForAppClientPage", unbilledYearParameter, unbilledMonthParameter, clientidParameter, lOBParameter);
        }
    
        public virtual ObjectResult<TimeSheetPieChartForApplicationDashboard_Result> TimeSheetPieChartForApplicationDashboard(Nullable<long> userid, string countryid, Nullable<long> unbilledYear, string unbilledMonth)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var countryidParameter = countryid != null ?
                new ObjectParameter("Countryid", countryid) :
                new ObjectParameter("Countryid", typeof(string));
    
            var unbilledYearParameter = unbilledYear.HasValue ?
                new ObjectParameter("UnbilledYear", unbilledYear) :
                new ObjectParameter("UnbilledYear", typeof(long));
    
            var unbilledMonthParameter = unbilledMonth != null ?
                new ObjectParameter("UnbilledMonth", unbilledMonth) :
                new ObjectParameter("UnbilledMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimeSheetPieChartForApplicationDashboard_Result>("TimeSheetPieChartForApplicationDashboard", useridParameter, countryidParameter, unbilledYearParameter, unbilledMonthParameter);
        }
    
        public virtual ObjectResult<timesheetmailhistory_1_Result> timesheetmailhistory_1(string employeeno, string timefrom, string timetill)
        {
            var employeenoParameter = employeeno != null ?
                new ObjectParameter("employeeno", employeeno) :
                new ObjectParameter("employeeno", typeof(string));
    
            var timefromParameter = timefrom != null ?
                new ObjectParameter("timefrom", timefrom) :
                new ObjectParameter("timefrom", typeof(string));
    
            var timetillParameter = timetill != null ?
                new ObjectParameter("timetill", timetill) :
                new ObjectParameter("timetill", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timesheetmailhistory_1_Result>("timesheetmailhistory_1", employeenoParameter, timefromParameter, timetillParameter);
        }
    
        public virtual ObjectResult<TimeSheetGrid1_Result> TimeSheetGrid1(string clientid, string lOB, Nullable<long> unbilledYear, string unbilledMonth)
        {
            var clientidParameter = clientid != null ?
                new ObjectParameter("clientid", clientid) :
                new ObjectParameter("clientid", typeof(string));
    
            var lOBParameter = lOB != null ?
                new ObjectParameter("LOB", lOB) :
                new ObjectParameter("LOB", typeof(string));
    
            var unbilledYearParameter = unbilledYear.HasValue ?
                new ObjectParameter("UnbilledYear", unbilledYear) :
                new ObjectParameter("UnbilledYear", typeof(long));
    
            var unbilledMonthParameter = unbilledMonth != null ?
                new ObjectParameter("UnbilledMonth", unbilledMonth) :
                new ObjectParameter("UnbilledMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimeSheetGrid1_Result>("TimeSheetGrid1", clientidParameter, lOBParameter, unbilledYearParameter, unbilledMonthParameter);
        }
    
        public virtual ObjectResult<TimeSheetGrid2_Result> TimeSheetGrid2(string clientid, string lOB, Nullable<long> unbilledYear, string unbilledMonth)
        {
            var clientidParameter = clientid != null ?
                new ObjectParameter("clientid", clientid) :
                new ObjectParameter("clientid", typeof(string));
    
            var lOBParameter = lOB != null ?
                new ObjectParameter("LOB", lOB) :
                new ObjectParameter("LOB", typeof(string));
    
            var unbilledYearParameter = unbilledYear.HasValue ?
                new ObjectParameter("UnbilledYear", unbilledYear) :
                new ObjectParameter("UnbilledYear", typeof(long));
    
            var unbilledMonthParameter = unbilledMonth != null ?
                new ObjectParameter("UnbilledMonth", unbilledMonth) :
                new ObjectParameter("UnbilledMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimeSheetGrid2_Result>("TimeSheetGrid2", clientidParameter, lOBParameter, unbilledYearParameter, unbilledMonthParameter);
        }
    
        public virtual ObjectResult<TimeSheetGrid3_Result> TimeSheetGrid3(string clientid, string lOB, Nullable<long> unbilledYear, string unbilledMonth)
        {
            var clientidParameter = clientid != null ?
                new ObjectParameter("clientid", clientid) :
                new ObjectParameter("clientid", typeof(string));
    
            var lOBParameter = lOB != null ?
                new ObjectParameter("LOB", lOB) :
                new ObjectParameter("LOB", typeof(string));
    
            var unbilledYearParameter = unbilledYear.HasValue ?
                new ObjectParameter("UnbilledYear", unbilledYear) :
                new ObjectParameter("UnbilledYear", typeof(long));
    
            var unbilledMonthParameter = unbilledMonth != null ?
                new ObjectParameter("UnbilledMonth", unbilledMonth) :
                new ObjectParameter("UnbilledMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimeSheetGrid3_Result>("TimeSheetGrid3", clientidParameter, lOBParameter, unbilledYearParameter, unbilledMonthParameter);
        }
    
        public virtual ObjectResult<TimeSheetappliGrid_Result> TimeSheetappliGrid(string clientid, string lOB, Nullable<long> unbilledYear, string unbilledMonth)
        {
            var clientidParameter = clientid != null ?
                new ObjectParameter("clientid", clientid) :
                new ObjectParameter("clientid", typeof(string));
    
            var lOBParameter = lOB != null ?
                new ObjectParameter("LOB", lOB) :
                new ObjectParameter("LOB", typeof(string));
    
            var unbilledYearParameter = unbilledYear.HasValue ?
                new ObjectParameter("UnbilledYear", unbilledYear) :
                new ObjectParameter("UnbilledYear", typeof(long));
    
            var unbilledMonthParameter = unbilledMonth != null ?
                new ObjectParameter("UnbilledMonth", unbilledMonth) :
                new ObjectParameter("UnbilledMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimeSheetappliGrid_Result>("TimeSheetappliGrid", clientidParameter, lOBParameter, unbilledYearParameter, unbilledMonthParameter);
        }
    
        public virtual int CLIENTUSER(Nullable<long> countryid, Nullable<long> userid)
        {
            var countryidParameter = countryid.HasValue ?
                new ObjectParameter("countryid", countryid) :
                new ObjectParameter("countryid", typeof(long));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CLIENTUSER", countryidParameter, useridParameter);
        }
    
        public virtual ObjectResult<CLIENTUSERMAPPING_Result> CLIENTUSERMAPPING(Nullable<long> countryid, Nullable<long> userid)
        {
            var countryidParameter = countryid.HasValue ?
                new ObjectParameter("countryid", countryid) :
                new ObjectParameter("countryid", typeof(long));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CLIENTUSERMAPPING_Result>("CLIENTUSERMAPPING", countryidParameter, useridParameter);
        }
    }
}
