//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_CLIENT_BRANCH
    {
        public long RID { get; set; }
        public long ClientID { get; set; }
        public string BranchName { get; set; }
        public long CityID { get; set; }
        public long StateID { get; set; }
        public long CountryID { get; set; }
        public string PinCode { get; set; }
        public short Status { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string WebSite { get; set; }
        public long ModifiedUserID { get; set; }
        public long CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public long BMUserID { get; set; }
        public string ORG_ACCESS { get; set; }
        public string VERT_ACCESS { get; set; }
        public short AccessType { get; set; }
        public string AccessManagerData { get; set; }
        public string AccessManagerQueryData { get; set; }
        public string SetCode { get; set; }
        public string DeptCode { get; set; }
        public long TeamTemplateID { get; set; }
        public string Prefix { get; set; }
        public long LastNumber { get; set; }
        public string Suffix { get; set; }
        public long HolidayTemplateID { get; set; }
        public short IsActive { get; set; }
        public string InvoiceAddress { get; set; }
        public long TaxCodesID { get; set; }
        public long BranchTypeID { get; set; }
        public long BranchManagerID { get; set; }
        public long NoticePeriod { get; set; }
        public string BranchNo { get; set; }
        public short EnablePPDiscount { get; set; }
        public string Notes { get; set; }
        public long BranchInvoiceStateID { get; set; }
        public string GSTNo { get; set; }
        public short ConsiderGPGPMConfigComputation { get; set; }
        public long ITRequirementGPGPM { get; set; }
        public long ITInputTypeGPGPM { get; set; }
        public decimal ITCompValueGPGPM { get; set; }
        public long NonITRequirementGPGPM { get; set; }
        public long NonITInputTypeGPGPM { get; set; }
        public decimal NonITCompValueGPGPM { get; set; }
        public decimal ITTargetGPM { get; set; }
        public decimal ITOtherCostPerc { get; set; }
        public decimal NonITTargetGPM { get; set; }
        public decimal NonITOtherCostPerc { get; set; }
        public string ExtContPayLoad { get; set; }
        public string ExtEmpPayLoad { get; set; }
    }
}
