//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_CONS_BILLING
    {
        public long RID { get; set; }
        public long ConsultantID { get; set; }
        public long ClientID { get; set; }
        public long ReqID { get; set; }
        public long ContactID { get; set; }
        public decimal BillingRate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public short Status { get; set; }
        public long ReasonID { get; set; }
        public Nullable<System.DateTime> LastBillDate { get; set; }
        public decimal LastBill { get; set; }
        public string CCID { get; set; }
        public decimal FixedAddition { get; set; }
        public decimal FixedDeduction { get; set; }
        public long TaxID { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public string Notes { get; set; }
        public long ReqResumeID { get; set; }
        public long CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string MonYear { get; set; }
        public System.DateTime LastBillRisedOn { get; set; }
        public decimal OfferedCTC { get; set; }
        public decimal BillableCTC { get; set; }
        public decimal InvoiceRate { get; set; }
        public decimal ServiceCharge { get; set; }
        public Nullable<System.DateTime> JoiningOn { get; set; }
        public short HiredByClientInvStatus { get; set; }
        public string ApproveNo { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public long OfferedCTCScale { get; set; }
        public decimal OfferedCTCFactor { get; set; }
        public long OfferedCTCCurrency { get; set; }
        public long BillableCTCScale { get; set; }
        public decimal BillableCTCFactor { get; set; }
        public long BillableCTCCurrency { get; set; }
        public long ProjectID { get; set; }
        public string EmployeeNo { get; set; }
        public long Frequency { get; set; }
        public string BillingItemIDs { get; set; }
        public decimal HOfferedCTC { get; set; }
        public long HOfferedCTCCurrency { get; set; }
        public long HOfferedCTCScale { get; set; }
        public decimal HOfferedCTCFactor { get; set; }
        public decimal HBillableCTC { get; set; }
        public long HBillableCTCCurrency { get; set; }
        public long HBillableCTCScale { get; set; }
        public decimal HBillableCTCFactor { get; set; }
        public long HBillingItemID { get; set; }
        public long CalculationTypeID { get; set; }
        public decimal FixedEarnings { get; set; }
        public long ApproveManagerID { get; set; }
        public long BranchID { get; set; }
        public decimal ComplimentaryOff { get; set; }
        public string ReimbursePONumber { get; set; }
        public Nullable<System.DateTime> ReimbursePODate { get; set; }
        public Nullable<System.DateTime> PayRollProcessedTill { get; set; }
        public Nullable<System.DateTime> PayRollDataLoadedTill { get; set; }
        public decimal AdvanceDays { get; set; }
        public string GroupNo { get; set; }
        public decimal HFPTAppliesAmount { get; set; }
        public decimal HFPTPaidAmount { get; set; }
        public long UpdatedUserID { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public short ProcessType { get; set; }
        public long ReportsToResumeID1 { get; set; }
        public long ReportsToResumeID2 { get; set; }
        public int POItemNumber { get; set; }
        public long DivisionID { get; set; }
        public string BillingItemText { get; set; }
        public decimal FixedDeductions { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ConsEffectiveDate { get; set; }
        public long InterviewVenue { get; set; }
        public string OfficialEmailID { get; set; }
        public long JoiningLocation { get; set; }
        public long HolidayTemplate { get; set; }
        public long OfflistTemplate { get; set; }
        public long InvoiceCurrency { get; set; }
        public short CurrencyFactor { get; set; }
        public short ExtisTimeSheetComplete { get; set; }
        public Nullable<System.DateTime> ExDOR { get; set; }
        public string ExBillingtool { get; set; }
        public string ExGLCode { get; set; }
        public string Exccc { get; set; }
        public long GradeID { get; set; }
        public short DiversityApplicable { get; set; }
        public decimal DiversityPercentage { get; set; }
        public string ExProName { get; set; }
        public string ExMonthlyCTC { get; set; }
        public Nullable<long> LTeamID { get; set; }
        public Nullable<long> LTeamIDOneDown { get; set; }
        public Nullable<long> LTeamIDTwoDown { get; set; }
        public Nullable<long> ConsProjectID { get; set; }
        public Nullable<short> LoadDataOf { get; set; }
        public Nullable<long> ProgramID { get; set; }
        public Nullable<System.DateTime> ExtPOEndDate { get; set; }
        public short InProcesscrtn { get; set; }
        public short ISAttrition { get; set; }
        public Nullable<System.DateTime> ERDateOfTerminationRecieved { get; set; }
        public long InvoiceFromStateID { get; set; }
        public long InvoiceToStateID { get; set; }
        public long BranchLocID { get; set; }
    }
}
