//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_EMAIL_SENT_LOG
    {
        public long rid { get; set; }
        public string employeeno { get; set; }
        public string TSStartdate { get; set; }
        public string TSEnddate { get; set; }
        public int TemplateId { get; set; }
        public Nullable<System.DateTime> EmailSent { get; set; }
        public Nullable<long> DateEmailSentUserId { get; set; }
        public string Comment { get; set; }
    }
}
