//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHD_Timesheet_Template
    {
        public long RID { get; set; }
        public Nullable<long> TemplateID { get; set; }
        public string TemplateName { get; set; }
        public string Name { get; set; }
        public string TemplateContent { get; set; }
        public List<TimeSheetDetailsAgainstCandidate_Result> history { get; set; }
        public string TemplateAttachment { get; set; }
    }
}
